kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone
spec:
  template:
    spec:
      containers:
        - name: drone
          env:
            - name: DRONE_GOGS_SERVER
              $patch: delete
            - name: DRONE_GITEA_CLIENT_ID
              valueFrom:
                  secretKeyRef:
                    key: gitea-client-id
                    name: drone-provider-gitea-id
            - name: DRONE_GITEA_CLIENT_SECRET
              valueFrom:
                  secretKeyRef:
                    key: gitea-client-secret
                    name: drone-provider-gitea-secret
            - name: DRONE_GITEA_SERVER
              value: http://gitea
