kind: Service
apiVersion: v1
metadata:
  name: drone
  labels:
    app: drone
spec:
  selector:
    app: drone
  ports:
    - port: 80
      targetPort: 80
      name: http

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone
  labels:
    app: drone
spec:
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: drone
        image: drone/drone:1.7.0
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: DRONE_AGENTS_ENABLED
          value: "true"

        - name: DRONE_LOGS_DEBUG
          value: "true"
        - name: DRONE_SERVER_HOST
          value: drone
        - name: DRONE_SERVER_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          value: secret
        - name: DRONE_GOGS_SERVER
          value: http://gogs
        - name: DRONE_TLS_AUTOCERT
          value: "false"
        - name: DRONE_DATABASE_DRIVER
          value: mysql
        - name: DRONE_DATABASE_DATASOURCE
          value: root:mytest@tcp(mysql)/drone?parseTime=true

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: minio-access-key
              name: minio-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: minio-secret-key
              name: minio-secret
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_REGION
          value: us-east-1
        - name: DRONE_S3_BUCKET
          value: drone
        - name: DRONE_S3_ENDPOINT
          value: http://minio:9000
        - name: DRONE_S3_PATH_STYLE
          value: "true"

        # 将值作为 webhooks 地址，drone 运行于内网，下面的值设为公网地址
        # - name: DRONE_SERVER_PROXY_HOST
        #   value: ""
        # - name: DRONE_SERVER_PROXY_PROTO
        #   value: https

        # - name: DRONE_WEBHOOK_ENDPOINT
        #   value: ""
        # - name: DRONE_WEBHOOK_EVENTS
        #   value: ""
        # - name: DRONE_WEBHOOK_SECRET
        #   value: ""
        # - name: DRONE_WEBHOOK_SKIP_VERIFY
        #   value: ""
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
      volumes:
      - name: data
        hostPath:
          path: /var/lib/ci/drone
          type: DirectoryOrCreate
