version: '3.4'
services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  drone-server:
    image: drone/drone:alpine
    networks:
      backend:
    ports:
      # - 80:80
      # - 443:443
      - "8000:8000"
      # - 9000:9000
    volumes:
      - drone-data:/var/lib/drone/:rw
      # - ${SSL_PATH}:/etc/certs
    restart: always
    environment:
      - DRONE_HOST=https://drone.t.khs1994.com
      - DRONE_SECRET=khs1994
      - DRONE_OPEN=true
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://git.t.khs1994.com

  drone-agent:
    image: drone/agent:alpine
    networks:
      backend:
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_SECRET=khs1994
      - DRONE_SERVER=drone-server:9000

  gogs:
    image: gogs/gogs
    networks:
      backend:
    ports:
      - "8022:22"
      - "10080:3000"
    volumes:
      - gogs-data:/data:rw
      - ./gogs/app.prod.ini:/data/gogs/conf/app.ini:ro
      - ./conf.d/ssl:/data/ssl:rw
    extra_hosts:
      - "drone.t.khs1994.com:${DRONE_IP}"

  mysql:
    image: mysql:5.7.20
    networks:
      backend:
    env_file: env/mysql.env
    # ports:
      # - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:rw
    command: ["mysqld","--character-set-server=utf8mb4"]

  registry:
    image: registry
    networks:
      backend:
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry:rw

  nginx:
    image: khs1994/nginx:1.13.6-alpine
    networks:
      backend:
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - registry
      - gogs
      - drone-server

networks:
  backend:

volumes:
  gogs-data:
  mysql-data:
  drone-data:
  registry-data:
