version: "3.7"

#
# This file override docker-compose.yml
#

x-ci:
  &production
  environment:
    - DRONE_GITHUB=true
    - DRONE_OPEN=${DRONE_OPEN:-false}
    - DRONE_HOST=http://khs1994.jios.org:18000
    - DRONE_SECRET=${DRONE_SECRET}
    - DRONE_ADMIN=khs1994,khs1994-merge-robot
    #
    - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT_TEST}
    - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET_TEST}
    #
    - DRONE_DATABASE_DRIVER=mysql
    - DRONE_DATABASE_DATASOURCE=root:mytest@tcp(mysql:3306)/gogs?parseTime=true

x-gogs:
  &gogs
  environment:
    - DRONE_GOGS=true
    - DRONE_OPEN=${DRONE_OPEN:-false}
    - DRONE_HOST={{ DRONE_HOST }}
    - DRONE_SECRET=${DRONE_SECRET}
    #
    - DRONE_GOGS_URL={{ DRONE_GOGS_URL }}
    - DRONE_GOGS_PRIVATE_MODE=${DRONE_GOGS_PRIVATE_MODE:-true}

x-github:
  &github
  environment:
    - DRONE_GITHUB=true
    - DRONE_OPEN=false
    - DRONE_HOST={{ DRONE_HOST }}
    - DRONE_SECRET=${DRONE_SECRET}
    #
    - DRONE_ADMIN=${DRONE_ADMIN}
    - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
    - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}

# Don't use this config
x-coding:
  &coding
  environment:
    - DRONE_CODING=true
    - DRONE_OPEN=false
    - DRONE_HOST={{ DRONE_HOST }}
    - DRONE_SECRET=${DRONE_SECRET}
    #
    - DRONE_CODING_CLIENT=${DRONE_CODING_CLIENT}
    - DRONE_CODING_SECRET=${DRONE_CODING_SECRET}

x-gitlab:
  &gitlab
  environment:
    - DRONE_GITLAB=true
    - DRONE_OPEN=false
    - DRONE_HOST={{ DRONE_HOST }}
    - DRONE_SECRET=${DRONE_SECRET}
    #
    - DRONE_GITLAB_CLIENT=${DRONE_GITLAB_CLIENT}
    - DRONE_GITLAB_SECRET=${DRONE_GITLAB_SECRET}
    - DRONE_GITLAB_URL={{ DRONE_GITLAB_URL }}

services:
  drone-server:
    << : *gogs
    # << : *github
    # << : *gitlab
    # << : *coding
    # << : *production

# networks:
#   backend:
#     external: true
#     name: lnmp_backend
#   frontend:
#     external: true
#     name: lnmp_frontend
