version: '3.4'
services:

  drone-server:
    image: drone/drone:${DRONE_VERSION}
    ports:
      # - 80:80
      # - 443:443
      - "${PUBLIC_IP}:8000:8000"
      # - 9000:9000
    volumes:
      - drone-data:/var/lib/drone/:rw
      # - ${SSL_PATH}:/etc/certs
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=${DRONE_GOGS_URL}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:${DRONE_VERSION}
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_SERVER=drone-server:9000
    dns: ${DNS}

volumes:
  gogs-data:
  mysql-data:
  drone-data:
  registry-data:
