version: '3.5'
services:

  drone-server:
    image: drone/drone:${DRONE_VERSION}
    restart: always
    ports:
      #
      # 如果没启用 https 则内部端口开放的是 8000 不是 80
      #
      # - 80:80
      # - 443:443
      - "${PUBLIC_IP}:8000:8000"
      # - 9000:9000
    volumes:
      - drone-data:/var/lib/drone/:rw
      # - ${SSL_PATH}:/etc/certs
    networks:
      - frontend
      - backend
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=${DRONE_GOGS_URL}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:${DRONE_VERSION}
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - backend
    environment:
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_SERVER=drone-server:9000

  gogs:
    image: gogs/gogs
    ports:
      - "22:22"
      - "3000:3000"
    networks:
      - frontend
      - backend
    volumes:
      - gogs-data:/data:rw
      - ./gogs/app.prod.ini:/data/gogs/conf/app.ini:ro
      - ./conf.d/ssl:/data/ssl:rw
    extra_hosts:
      - "drone.${DOMAIN}:${DRONE_IP}"

volumes:
  drone-data:
  gogs-data:
