version: '3.5'
services:

# 出现错误，请勿使用

# http://docs.drone.io/install-for-coding


# drone-server_1  | time="2017-11-17T04:12:04Z" level=fatal msg="version control system not configured"
# drone-agent_1   | {"time":"2017-11-17T04:12:05Z","level":"debug","message":"request next execution"}
# ci_drone-server_1 exited with code 1
# drone-server_1  | time="2017-11-17T04:12:04Z" level=fatal msg="version control system not configured"
# drone-server_1  | time="2017-11-17T04:12:05Z" level=fatal msg="version control system not configured"
# drone-server_1  | time="2017-11-17T04:12:07Z" level=fatal msg="version control system not configured"
# drone-agent_1   | INFO: 2017/11/17 04:12:07 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 172.19.0.2:9000: getsockopt: connection refused"; Reconnecting to {drone-server:9000 <nil>}
# drone-agent_1   | INFO: 2017/11/17 04:12:07 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 172.19.0.2:9000: getsockopt: connection refused"; Reconnecting to {drone-server:9000 <nil>}

  drone-server:
    image: drone/drone:${DRONE_VERSION}
    ports:
      - 8000:8000
    volumes:
      - drone-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST_PRO}
      - DRONE_CODING=true
      - DRONE_CODING_CLIENT=${DRONE_CODING_CLIENT}
      - DRONE_CODING_SECRET=${DRONE_CODING_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:${DRONE_VERSION}
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}

volumes:
  drone-data:
