#
# CI/CD 私有化部署基于端口版
#

version: "3.6"

x-common:
  &default-common
  restart: always
  networks:
    - backend

services:

  drone-server:
    << : *default-common
    image: drone/drone:${CI_DRONE_VERSION:-0.8.5}
    ports:
      # - 80:80
      # - 443:443
      - "${CI_BASED_PORT_DRONE_HOST}:${CI_BASED_PORT_DRONE_PORT:-8000}:8000"
      # - 9000:9000
    volumes:
      - drone-data:/var/lib/drone/:rw
    networks:
      - frontend
      - backend

  drone-agent:
    << : *default-common
    image: drone/agent:${CI_DRONE_VERSION:-0.8.5}
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_SERVER=drone-server:9000

  gogs:
    << : *default-common
    image: gogs/gogs
    ports:
      - "${CI_BASED_PORT_DRONE_HOST}:${CI_BASED_PORT_GOGS_SSH_PORT}:22"
      - "${CI_BASED_PORT_DRONE_HOST}:${CI_BASED_PORT_GOGS_PORT}:3000"
    networks:
      - frontend
      - backend
    volumes:
      - gogs-data:/data:rw
      - ./gogs/app.port.ini:/data/gogs/conf/app.ini:ro

  registry:
    << : *default-common
    image: registry
    ports:
      - "${CI_BASED_PORT_DRONE_HOST}:${CI_BASED_PORT_REGISTRY_PORT:-5000}:5000"
    networks:
      - frontend
      - backend
    volumes:
      - ./registry/config.port.yml:/etc/docker/registry/config.yml:ro
      - registry-data:/var/lib/registry:rw

  mysql:
    << : *default-common
    image: mysql:{CI_MYSQL_VERSION:-8.0.3}
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql:rw
    command: ["mysqld","--character-set-server=utf8mb4"]

  redis:
    << : *default-common
    image: redis:${CI_REDIS_VERSION:-4.0.9}-alpine
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:${CI_NGINX_VERSION:-1.13.11}-alpine
    networks:
      - frontend
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

volumes:
  gogs-data:
  redis-data:
  mysql-data:
  drone-data:
  registry-data:

networks:
  backend:
  frontend:
