version: "3.5"

services:

  drone-github-server:
    image: drone/drone:${DRONE_VERSION}
    restart: always
    ports:
      - "${DRONE_HOST_BASED_PORT}:18000:8000"
    # volumes:
    #   - drone-github-data:/var/lib/drone/:rw
    networks:
      - frontend
      - backend
    environment:
      #
      #
      # GitHub
      #
      #
      - DRONE_OPEN=false
      - DRONE_ADMIN=khs1994,khs1994-merge-robot
      - DRONE_HOST=http://khs1994.jios.org:18000
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT_TEST}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET_TEST}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=root:mytest@tcp(mysql:3306)/gogs?parseTime=true

  drone-github-agent:
    image: drone/agent:${DRONE_VERSION}
    restart: always
    depends_on:
      - drone-github-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - backend
    environment:
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_SERVER=drone-github-server:9000

# volumes:
#   drone-github-data:
