kind: Service
apiVersion: v1
metadata:
  name: drone
  labels:
    app: drone-kubenative
spec:
  selector:
    app: drone-kubenative

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone
  labels:
    app: drone-kubenative
spec:
  selector:
    matchLabels:
      app: drone-kubenative
  template:
    metadata:
      labels:
        app: drone-kubenative
    spec:
      serviceAccountName: drone-kubenative
      containers:
      - name: drone
        env:
        # https://docs.drone.io/installation/reference/
        - name: DRONE_AGENTS_ENABLED
          value: "false"
        - name: DRONE_KUBERNETES_ENABLED
          value: "true"
        - name: DRONE_KUBERNETES_NAMESPACE
          value: "ci"
        # 同步修改 rbac-pipeline.yaml
        - name: DRONE_KUBERNETES_SERVICE_ACCOUNT
          value: "drone-pipeline-kubenative"
        - name: DRONE_SERVER_HOST
          value: drone-kubenative
        - name: DRONE_S3_BUCKET
          value: drone-kubenative
