# pipeline 的 pod
# sa 为 drone-pipeline-kubenative 由 DRONE_KUBERNETES_SERVICE_ACCOUNT 控制
# ns 为 ci
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-pipeline
  labels:
    app: drone-pipeline-kubenative
    tier: kubernetes

---

# pipeline 需要的权限
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: drone-pipeline-kubenative
    tier: kubernetes
  name: drone:drone-pipeline
rules:
- apiGroups: [""]
  resources: ["secrets","pods","configmaps","namespaces","services"]
  verbs: ["create","delete","update","get","list","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get","list","watch","patch","update"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone:drone-pipeline
  labels:
    app: drone-pipeline-kubenative
    tier: kubernetes
subjects:
- kind: ServiceAccount
  name: drone-pipeline
  namespace: ci
roleRef:
  kind: ClusterRole
  name: drone:drone-pipeline
  apiGroup: ""
