kind: Service
apiVersion: v1
metadata:
  name: drone
  labels:
    app: drone-kubenative
spec:
  selector:
    app: drone-kubenative

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone
  labels:
    app: drone-kubenative
spec:
  selector:
    matchLabels:
      app: drone-kubenative
  template:
    metadata:
      labels:
        app: drone-kubenative
    spec:
      serviceAccountName: drone-kubenative
      containers:
      - name: drone
        env:
        - name: DRONE_AGENTS_ENABLED
          value: "false"
        - name: DRONE_KUBERNETES_ENABLED
          value: "true"
        - name: DRONE_KUBERNETES_NAMESPACE
          value: "ci"
        # 同步修改 rbac-runner.yaml
        - name: DRONE_KUBERNETES_SERVICE_ACCOUNT
          value: "drone-runner-kubenative"

        - name: DRONE_LOGS_DEBUG
          value: "true"
        - name: DRONE_SERVER_HOST
          value: drone-kubenative
        - name: DRONE_SERVER_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          value: secret
        - name: DRONE_GOGS_SERVER
          value: http://gogs
        - name: DRONE_TLS_AUTOCERT
          value: "false"
        - name: DRONE_DATABASE_DRIVER
          value: mysql
        - name: DRONE_DATABASE_DATASOURCE
          value: root:mytest@tcp(mysql)/droneKubenative?parseTime=true

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: minio-access-key
              name: minio-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: minio-secret-key
              name: minio-secret
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_REGION
          value: us-east-1
        - name: DRONE_S3_BUCKET
          value: drone-kubenative
        - name: DRONE_S3_ENDPOINT
          value: http://minio:9000
        - name: DRONE_S3_PATH_STYLE
          value: "true"

        # 将值作为 webhooks 地址，drone 运行于内网，下面的值设为公网地址
        # - name: DRONE_SERVER_PROXY_HOST
        #   value: ""
        # - name: DRONE_SERVER_PROXY_PROTO
        #   value: https

        # - name: DRONE_WEBHOOK_ENDPOINT
        #   value: ""
        # - name: DRONE_WEBHOOK_EVENTS
        #   value: ""
        # - name: DRONE_WEBHOOK_SECRET
        #   value: ""
        # - name: DRONE_WEBHOOK_SKIP_VERIFY
        #   value: ""
