kind: PersistentVolume
apiVersion: v1
metadata:
  name: ci-mysql-data-pv
  labels:
    app: ci
    tier: mysql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/k8s/ci/mysql
    type: DirectoryOrCreate
  storageClassName: hostpath

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ci-log-pv
  labels:
    app: ci
    tier: log
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/k8s/ci/log
    type: DirectoryOrCreate
  storageClassName: hostpath
