kind: PersistentVolume
apiVersion: v1
metadata:
  name: ci-redis-data-pv
  labels:
    app: ci
    tier: redis
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/ci/redis
  storageClassName: hostpath
