kind: Service
apiVersion: v1
metadata:
  name: drone-runner-docker-dashboard
spec:
  selector:
    app: drone-runner
    tier: docker
  ports:
    - port: 3000
      targetPort: 3000
      name: dashboard
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone-runner-docker
  labels:
    app: drone-runner
    tier: docker
spec:
  selector:
    matchLabels:
      app: drone-runner
      tier: docker
  template:
    metadata:
      labels:
        app: drone-runner
        tier: docker
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: drone-runner-docker
        image: drone/drone-runner-docker:1
        env:
        # https://docker-runner.docs.drone.io/installation/reference/
        - name: DRONE_RPC_SECRET
          value: secret
        - name: DRONE_RPC_HOST
          value: drone
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RUNNER_NAME
          value: docker
        - name: DRONE_RUNNER_CAPACITY
          value: "2"
        - name: DRONE_DEBUG
          value: "true"
        - name: DRONE_UI_USERNAME
          value: root
        - name: DRONE_UI_PASSWORD
          value: root
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        ports:
          - containerPort: 3000
            name: dashboard
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
