kind: PersistentVolume
apiVersion: v1
metadata:
  name: ci-minio
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /var/lib/k8s/ci/minio
    type: DirectoryOrCreate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: minio
  storageClassName: hostpath
